services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
      - redis
      - static
    restart: always

  redis:
    build:
      context: ./requirements/redis
    image: redis
    container_name: redis
    networks:
      - inception
    restart: always

  adminer:
    build:
      context: ./requirements/adminer
    image: adminer
    container_name: adminer
    networks:
      - inception
    restart: always

  static:
    build:
      context: ./requirements/static
    image: static
    container_name: static
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dlemaire/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/dlemaire/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
